### ISSUE TITLE
Could you give an example of an image frame in the byte array format from Karpathy's Blog?

### ISSUE THREAD

**Issue by hirehamir** [gauravkuppa/pong-from-pixels#10]
That is, would you be able to give an example of how, given an image, one would represent that image using "a 210x160x3 byte array (integers from 0 to 255 giving pixel values)"?

http://karpathy.github.io/2016/05/31/rl/

**Comment by gauravkuppa** [comment]
So, the dimensions 210 and 160 are the height and width of the image. In other words, the image is 210 pixels high and 160 pixels wide. I hope that part makes sense. 

Each pixel, in real life, is represented through an RGB value. RGB values have a domain of [0, 255) for each color channel.

![image](https://user-images.githubusercontent.com/24405632/80127767-a83e8d80-8549-11ea-90ee-fa8dfaf733eb.png)

Each color channel, R, G, and B, represents the depth of the image. Now, a single pixel is represented as a color with the combination of bytes in the R G and B space. The word byte is used because bytes represent a value with 8 bits. 8 bit values, or a byte, can represent integers (0 - 255). I will let you do that math out by yourself.
